#!name=LimbusCompany IOS Localization
#!desc=边狱巴士ios汉化模块 by ghcruise

[URL Rewrite]
^https?://.*localize_en.zip$ https://github.com/Ming900907/LimbusCompany-IOS-Localization/releases/latest/download/localize_en.zip 302

^https://downloadcommon\.limbuscompanycdn\.org/.*LocalizePatchInfo\.json$ https://github.com/Ming900907/LimbusCompany-IOS-Localization/releases/latest/download/manifest.json 302

[MITM]
hostname = *.limbuscompanycdn.org
